apiVersion: v1
kind: ConfigMap
metadata:
  name: student-management-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: "/student"
