apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  selector:
    app: student-management-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30080
  type: NodePort
